### ISSUE TITLE
(At least) error when pinging bungee 1.9

### ISSUE THREAD

**Issue by Janmm14** [geNAZt/minecraft-status#1]
```
2016/03/06 14:19:00 ^[[1;33m[proc.c:1445] [W] Error while pinging: json: cannot unmarshal object into Go value of type string^[[0m
```

This error occurrs when the minecrafttracker tries to ping minotopia.me and mineplex.com (maybe also if its about cubecraftgames).

**Comment by geNAZt** [comment]
Should be fixed

**Comment by Janmm14** [comment]
Thanks! It worked after readding the ping.go class.
